// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace infersharp_vs_ext
{
    internal sealed partial class Vsix
    {
        public const string Id = "infersharp_vs_ext.c28d99a5-39d6-47e4-8e51-c181f4b02ede";
        public const string Name = "InferSharp";
        public const string Description = @"Visual Studio extension experience for InferSharp https://github.com/microsoft/infersharp

";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "matthew-jin";
        public const string Tags = "";
    }
}
